name: Run Telegram Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes to stay alive

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Start the bot in background
        python app.py &
        # Keep the action running (important!)
        sleep 300  # 5 minutes
